#!/usr/bin/env python
import sys
import os
import subprocess

remap = ''
drive_letters = os.listdir('/mnt')
for i, arg in enumerate(sys.argv):
    for letter in drive_letters:
        assert(len(letter) == 1)
        letter_path = letter + ':\\'
        if arg[0:3].lower() == letter_path:
            sys.argv[i] = 'c:\\' + arg[3:]
            remap = letter

sys.argv[0] = '/bin/wslpath'
p = subprocess.Popen(sys.argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = p.communicate()
if p.returncode == 0:
    assert out.startswith('/mnt/c/')
    out = '/mnt/' + remap + '/' + out[7:]
sys.stderr.write(err)
sys.stdout.write(out)
sys.exit(p.returncode)

